---
version: '2'
services:
  data:
    container_name: data
    image: tianon/true:latest
    volumes:
      - ./data/opt/hailo:/opt/hailo
      - ./data/cassandra:/var/lib/cassandra
      - ./data/rabbitmq:/var/lib/rabbitmq
      - ./data/etc/h2o:/etc/h2o
    command: "/true"
